trunk/Sphera/sphera/src/br/com/sphera/entities/Usuario.java
package br.com.sphera.entities;

import java.io.Serializable;
import java.util.List;

public class Usuario implements Serializable {
	private Long id;
	private String nome;
	private boolean ativo;
	private String login;
	private String senha;
	private String email;
	private Double custoHora;
	private String telefone;
	private List<Tarefa> tarefas;
	private Departamento departamento;
	private Cargo cargo;
	private List<Perfil> perfis;

	public Usuario() {
		setAtivo(true);
	}
	public Usuario(String nome, String login, String senha, String email, Double custoHora) {
		this();
		setNome(nome);
		setLogin(login);
		setSenha(senha);
		setEmail(email);
		setCustoHora(custoHora);
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public boolean isAtivo() {
		return ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Double getCustoHora() {
		return custoHora;
	}

	public void setCustoHora(Double custoHora) {
		this.custoHora = custoHora;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public List<Tarefa> getTarefas() {
		return tarefas;
	}

	public void setTarefas(List<Tarefa> tarefas) {
		this.tarefas = tarefas;
	}

	public Departamento getDepartamento() {
		return departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	public Cargo getCargo() {
		return cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	public List<Perfil> getPerfis() {
		return perfis;
	}

	public void setPerfis(List<Perfil> perfis) {
		this.perfis = perfis;
	}
	@Override
	public String toString() {
		return nome+" ("+login+")";
	}
}

trunk/Sphera/sphera/src/br/com/sphera/mbean/UsuarioController.java
package br.com.sphera.mbean;

import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpSession;

import br.com.sphera.entities.Usuario;
import br.com.sphera.fake.dao.UsuarioDAO;
import br.com.sphera.util.JSFUtil;

public class UsuarioController{

	private Usuario usuario;
	private List<Usuario> usuarios;
	private UsuarioDAO dao;
	private String confirmSenha;
	private String selectedTab = "tabList";
	private boolean creating = true;
	private String name;
	
	public UsuarioController() {
		usuario = new Usuario();
	}
	public List<Usuario> autocomplete(Object suggest){
		return dao.findUserNameStartWith(String.valueOf(suggest));
	}
	public void setDao(UsuarioDAO dao) {
		this.dao = dao;
	}
	public List<Usuario> getUsuarios() {
		usuarios = dao.listAll();
		return usuarios;
	}
	public List<SelectItem> getComboList(){
		List<Usuario> users = getUsuarios();
		List<SelectItem> itens = new ArrayList<SelectItem>();
		for (Usuario user : users) {
			itens.add(new SelectItem(user,user.getNome()));
		}
		return itens;
	}
	public Usuario getUsuario() {
		return usuario;
	}
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	public String save(){
		if (!creating && !usuario.getSenha().equals(confirmSenha)){
			FacesContext context = FacesContext.getCurrentInstance();
			ResourceBundle rb = context.getApplication().getResourceBundle(context, "i18n");
			JSFUtil.addErrorMessage("valueNotEqual", "user:senhaConf", rb.getString("lblConfSenha"),rb.getString("lblSenha"));
			return null;
		}else{
			usuario.setSenha(name);
		}
		
		this.dao.save(usuario);
		JSFUtil.addInfoMessage("sucessSavedUser", null);
		return "usuarios";
	}
	public String list(){
		return "usuarios";
	}
	public String delete(){
		System.out.println("delete user: "+usuario.getNome());
		dao.delete(usuario);
		JSFUtil.addInfoMessage("sucessDeletedUser", null);
		return null;
	}
	public void edit(ActionEvent event){
		System.out.println("edit user: "+usuario.getNome());
		selectedTab = "tabCreate";
		setCreating(false);
		setName(usuario.getSenha());
	}
	
	public String getConfirmSenha() {
		return confirmSenha;
	}
	public void setConfirmSenha(String confirmEmail) {
		this.confirmSenha = confirmEmail;
	}
	public void viewUser(){
		System.out.println("view user: "+usuario.getNome());
	}
	public String getSelectedTab() {
		return selectedTab;
	}
	public void setSelectedTab(String selectedTab) {
		this.selectedTab = selectedTab;
	}
	public boolean isCreating() {
		return creating;
	}
	public void setCreating(boolean isEdit) {
		this.creating = isEdit;
	}
	public String getName() {
		return name;
	}
	public void setName(String hidden) {
		this.name = hidden;
	}
	
	public String login() {
		Usuario user = dao.readByLogin(this.usuario);
		
		FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("user", user);			
		
		return "login";
	}
	
	public String logout() {
		
		HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
		
		session.invalidate();
		
		return "logout";
	}
}

trunk/Sphera/sphera/WebContent/app/usuario/create.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:sphera="http://org.sphera/mytags"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
	
	<a4j:region id="regUser" selfRendered="false" renderRegionOnly="true">
		<h:form id="user">
			<h:inputHidden value="#{usuarioController.usuario.id}"/>
		
			<h:panelGrid  width="70%" columns="3" columnClasses="colunOne,colunTwo,colunThree" id="fields">
				<h:outputLabel value="#{i18n.lblNome}" for="nome" />
				<h:inputText value="#{usuarioController.usuario.nome}" id="nome" label="#{i18n.lblNome}" required="true"/>
				<sphera:message validID="nome"/>
			
				<h:outputLabel value="#{i18n.lblLogin}" for="login" />
				<h:inputText required="true" value="#{usuarioController.usuario.login}" id="login" label="#{i18n.lblLogin}" />
				<sphera:message validID="login"/>
				
				<h:outputLabel rendered="#{usuarioController.creating}" value="#{i18n.lblSenha}" for="senha" />
				<h:inputSecret rendered="#{usuarioController.creating}" required="true" value="#{usuarioController.usuario.senha}" id="senha" label="#{i18n.lblSenha}" > 
					<f:validateLength maximum="15" minimum="5"/>
				</h:inputSecret>
					
				<a4j:outputPanel rendered="#{usuarioController.creating}" ajaxRendered="true">
					<h:outputText value=" " rendered="#{empty facesContext.maximumSeverity.ordinal}" />
					<rich:message for="senha">
						<f:facet name="errorMarker">
							<h:graphicImage value="/images/error.gif" />
						</f:facet>
					</rich:message>
				</a4j:outputPanel>
					
				<h:outputLabel rendered="#{usuarioController.creating}"  value="#{i18n.lblConfSenha}" for="senhaConf" />
				<h:inputSecret rendered="#{usuarioController.creating}"  required="true" value="#{usuarioController.confirmSenha}" id="senhaConf" label="#{i18n.lblConfSenha}" >
					<f:validateLength maximum="15" minimum="5"/>	
				</h:inputSecret>
				<a4j:outputPanel rendered="#{usuarioController.creating}" ajaxRendered="true">
					<h:outputText value=" " rendered="#{empty facesContext.maximumSeverity.ordinal}" />
					<rich:message for="senhaConf">
						<f:facet name="errorMarker">
							<h:graphicImage value="/images/error.gif" />
						</f:facet>
					</rich:message>
				</a4j:outputPanel>
				
				<h:outputLabel value="#{i18n.lblDept}" for="dpt" />
				<h:selectOneMenu label="#{i18n.lblDept}" value="#{usuarioController.usuario.departamento}" id="dpt" >
					<f:selectItems value="#{departamentoController.comboList}"/>
					<f:converter converterId="deptConvert"/>
				</h:selectOneMenu>
				<sphera:message validID="dpt"/>
				
				<h:outputLabel value="#{i18n.lblCargo}" for="cargo" />
				<h:selectOneMenu label="#{i18n.lblCargo}" value="#{usuarioController.usuario.cargo}" id="cargo">
					<f:selectItems value="#{cargoController.comboList}"/>
					<f:converter converterId="cargoConvert"/>
				</h:selectOneMenu>
				<sphera:message validID="cargo"/>
				
				<h:outputLabel value="#{i18n.lblPerfil}" for="perfil"/>
				<h:selectManyListbox size="3" id="perfil" value="#{usuarioController.usuario.perfis}" required="true">
					<f:selectItems value="#{perfilController.comboList}"/>
				</h:selectManyListbox>
				<sphera:message validID="perfil"/>
				
				<h:outputLabel value="#{i18n.lblCusto}" for="custo" />
				<h:inputText  required="true" value="#{usuarioController.usuario.custoHora}" id="custo" label="#{i18n.lblCusto}" />
				<sphera:message validID="custo"/>
				
				<h:outputLabel value="#{i18n.lblEmail}" for="email" />
				<h:inputText  required="true" value="#{usuarioController.usuario.email}" id="email" label="#{i18n.lblEmail}" >
					<f:validator validatorId="emailValid"/>
				</h:inputText>
				<sphera:message validID="email"/>
				
				<h:outputLabel value="#{i18n.lblTel}" for="tel" />
				<h:inputText value="#{usuarioController.usuario.telefone}" id="tel" label="#{i18n.lblTel}" />
				<sphera:message validID="tel"/>				
			</h:panelGrid>
				<h:inputHidden value="#{usuarioController.name}"  />
			<h:panelGrid columns="2">
				<a4j:commandButton action="#{usuarioController.save}" value="#{i18n.save}" />
				<h:commandButton action="usuarios" value="#{i18n.cancel}" immediate="true"/>
			</h:panelGrid>
		</h:form>
</a4j:region>
</ui:composition>

trunk/Sphera/sphera/WebContent/app/usuario/list.xhtml
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

		<h:form id="list">
			<rich:dataTable id="userList" value="#{usuarioController.usuarios}" var="user" rows="20" rendered="#{not empty usuarioController.usuarios}">
				<rich:column filterEvent="onkeyup" filterBy="#{user.nome}" sortBy="#{user.nome}">
					<f:facet name="header">
						<h:outputText value="#{i18n.lblNome}"/>
					</f:facet>
					<h:outputText value="#{user.nome}"/>
				</rich:column>	
				<rich:column filterEvent="onkeyup" filterBy="#{user.login}" sortBy="#{user.login}">
					<f:facet name="header">
						<h:outputText value="#{i18n.lblLogin}"/>
					</f:facet>
					<h:outputText value="#{user.login}"/>
				</rich:column>	
				<rich:column  filterEvent="onkeyup" filterBy="#{user.email}" sortBy="#{user.email}">
					<f:facet name="header">
						<h:outputText value="#{i18n.lblEmail}"/>
					</f:facet>
					<h:outputText value="#{user.email}"/>
				</rich:column>
				<rich:column>
						<f:facet name="header">
							<h:outputText value="#{i18n.actions}"/>
						</f:facet>
						<h:panelGrid columns="3">
							<a4j:commandLink actionListener="#{usuarioController.edit}" value="#{i18n.edit}" reRender="tabPanel">
								<f:setPropertyActionListener value="#{user}" target="#{usuarioController.usuario}" />
							</a4j:commandLink>
							<h:outputLink value="#" onclick="#{rich:component('confirm')}.show()" >
								<h:outputText value="#{i18n.delete}" id="del"/>
							</h:outputLink>
							
							
							<a4j:commandLink value="#{i18n.view}" id="viewGo" action="#{usuarioController.viewUser}" reRender="view" oncomplete="#{rich:component('view')}.show()">
									<f:setPropertyActionListener value="#{user}" target="#{usuarioController.usuario}" />
							</a4j:commandLink>
							
							<rich:modalPanel id="confirm" width="150" height="80">
								<f:facet name="header">
									<h:outputText value="#{i18n.confirmDelete}"/>
								</f:facet>
								<table align="center">
									<tr>
										<td align="center">
											<a4j:commandButton value="#{i18n.confirmOk}" id="doAct" action="#{usuarioController.delete}" reRender="userList,message">
												<rich:componentControl attachTo="doAct" for="confirm" operation="hide" event="onclick">
												</rich:componentControl>
												<f:setPropertyActionListener value="#{user}" target="#{usuarioController.usuario}" />
											</a4j:commandButton>
										</td>
										<td align="center">
											<input type="button" value="#{i18n.confirmCancel}" onclick="#{rich:component('confirm')}.hide()"/>
										</td>
									</tr>
								</table>
							</rich:modalPanel>
							
						</h:panelGrid>
					</rich:column>
					<f:facet name="footer">
						<rich:datascroller for="userList" renderIfSinglePage="false" bypassUpdates="true" ajaxSingle="true" id="scrol" immediate="true" maxPages="3" reRender="tabPanel"/>
					</f:facet>		
			</rich:dataTable>
			
		</h:form>

</ui:composition>

trunk/Sphera/sphera/WebContent/app/usuario/tab.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:sphera="http://org.sphera/mytags">
<ui:composition template="/templates/template.xhtml">
	<ui:define name="body">
	<a4j:outputPanel ajaxRendered="true">
		<h:messages globalOnly="true" layout="table" id="message" errorClass="rich-message-label" infoClass="info-message"/>
	</a4j:outputPanel>
		
		<rich:tabPanel id="tabPanel" switchType="ajax" height="400px;"
			width="600px;" selectedTab="#{usuarioController.selectedTab}">
			<rich:tab label="Listar" id="tabList">
				<ui:include src="list.xhtml" />
			</rich:tab>
			<rich:tab label="Criar" id="tabCreate">
				<ui:include src="create.xhtml" />
			</rich:tab>
		</rich:tabPanel>
		<rich:modalPanel id="view" width="300" height="300">
			<f:facet name="header">
				<h:outputText value="#{i18n.user}"/>
			</f:facet>
			<f:facet name="controls">
				<h:graphicImage value="/images/close.png" style="cursor:pointer"
				onclick="#{rich:component('view')}.hide()" />
			</f:facet>
			<div align="center"><ui:include src="view.xhtml" /></div>
		</rich:modalPanel>
	</ui:define>
</ui:composition>

</html>

trunk/Sphera/sphera/WebContent/app/usuario/view.xhtml


<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a4j="http://richfaces.org/a4j">

	<h:panelGrid columns="2" columnClasses="col-aling-lef" width="100%">
		<h:outputText id="lblNome" value="#{i18n.lblNome}" />
		<h:outputText id="name" value="#{usuarioController.usuario.nome}" />
		<h:outputText id="lblLogin" value="#{i18n.lblLogin}" />
		<h:outputText id="login" value="#{usuarioController.usuario.login}" />
		<h:outputText
			rendered="#{not empty usuarioController.usuario.departamento}"
			value="#{i18n.lblDept}" id="lblDept" />
		<h:outputText
			rendered="#{not empty usuarioController.usuario.departamento}"
			id="dept" value="#{usuarioController.usuario.departamento}" />
		<h:outputText rendered="#{not empty usuarioController.usuario.cargo}"
			id="lblCargo" value="#{i18n.lblCargo}" />
		<h:outputText rendered="#{not empty usuarioController.usuario.cargo}"
			value="#{usuarioController.usuario.cargo}" id="cargo" />
		<h:outputText value="#{i18n.lblEmail}" />
		<h:outputText value="#{usuarioController.usuario.email}" id="email" />
		<h:outputText
			rendered="#{not empty usuarioController.usuario.telefone}"
			value="#{i18n.lblTel}" id="lblTel" />
		<h:outputText
			rendered="#{not empty usuarioController.usuario.telefone}"
			value="#{usuarioController.usuario.telefone}" id="tel" />
	</h:panelGrid>



</ui:composition>